### ISSUE TITLE
Shockwave applet for connecting pictures and words is not loaded

### ISSUE THREAD

**Issue by gioele** [cceh/palonline#2]
The Shockwave applet that is used to connect areas of the pictures to transcribed words is not loaded, so there is no way for the lecturers to transcribe new pictures.

**Comment by gioele** [comment]
To see this error visit the page

    vhb_intern/modulobjekt.php?bildschirm_ID=32&stundenplan_ID=

**Comment by olvidalo** [comment]
applet Admin_Pal.dcr was missing

fixed with 4a81c93ee9902d9120a1a7cee1b5980807090962.

**Comment by GVogeler** [comment]
I've still problems:

**Comment by gioele** [comment]
Could I ask you to check again? The data passed to the Shockwave applet in that page is

    eminem,iam,esse,hominem,arbitror,quem,latere,possit [...]

and that should be the correct data IIUC.

**Comment by GVogeler** [comment]
Still the same (using chrome Version 41.0.2272.118, Shockwave Plyer 12.1.7.157)
Other example http://www.palaeographie-online.de/vhb_intern/modulobjekt.php?bildschirm_ID=222&stundenplan_ID=76
![clipboard01](https://cloud.githubusercontent.com/assets/324006/7071418/7442cf38-dee5-11e4-82fb-47e4a5e3b049.png)
which should read "uris traditionisque causam accepit quae supra venditrex quam"

**Comment by gioele** [comment]
The HTML code passes the correct data to the Shockwave applet:

    <param name="sw8"
        value="uris,traditionis,que,causam,accepit,quae,supra,venditrex,quam">

Where does the Shockwave applet take its data?

**Comment by gioele** [comment]
I leaning towards the idea that this is just a configuration problem (Shockwave may be calling the wrong `postdata.php`). I have changed some paths now and I hope this may solve the problem.

**Comment by GVogeler** [comment]
unfortunately not
Next example: http://www.palaeographie-online.de/vhb_intern/modulobjekt.php?bildschirm_ID=32&stundenplan_ID=37
![clipboard01](https://cloud.githubusercontent.com/assets/324006/7087646/c8649800-df8d-11e4-8b89-16b872a204c2.png)
